remote_theme: tuur29/pages-themes-cayman
plugins:
- jekyll-remote-theme

title: The Grieshaber-Bouyer Laboratory
description: Systems Immunology at Heidelberg University Hospital

show_downloads: true
google_analytics: [Google Analytics tracking ID]

google_analytics_anonymize: false
darkmode: true
hide_first_title: true # Useful if README.md is used on both github and pages
# logo_url: ./logo.png # Either absolute or relative url
# syntax_theme: ./syntax.css # Leave empty for default, otherwise link to a pygments stylesheet
colors:
    gradient_left: "#104172"
    gradient_right: "#710083"
    header: "#fff"
    android_theme: "#000" # this default to gradient_color
    link: "#1e6bb8" # this default to gradient_color
    section_title: "#155799" # this default to gradient_color
 buttons:
      zip_url: https://rgb-lab.de/publications
      zip_title: Publications
      zip_hide: false
      tar_url: https://rgb-lab.de/team
      tar_title: Team
      tar_hide: false
      github_hide: true
